networks:
  ros2_project_example:

services:
  sub:
    image: ncotti/ros2:project_example

    container_name: sub

    environment:
      # Required for GUI
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    volumes:
      # Required for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${PWD}/entrypoint.sh:/entrypoint.sh
      - ${PWD}/../${PKG_NAME}:/root/dev_ws/src/${PKG_NAME}
      - ${PWD}/../my_interface:/root/dev_ws/src/my_interface

    tty: true

    networks:
      - ros2_project_example

    command: "ros2 run my_package subscriber"

  pub:
    image: ncotti/ros2:project_example

    container_name: pub

    environment:
      # Required for GUI
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    volumes:
      # Required for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${PWD}/entrypoint.sh:/entrypoint.sh
      - ${PWD}/../${PKG_NAME}:/root/dev_ws/src/${PKG_NAME}
      - ${PWD}/../my_interface:/root/dev_ws/src/my_interface

    tty: true

    networks:
      - ros2_project_example

    command: "ros2 run my_package publisher"