services:
  ros:
    image: ncotti/ros2:project_example

    build:
      context: ${PWD}/..
      dockerfile: Docker/Dockerfile
      args:
        - PKG_NAME=${PKG_NAME}

    container_name: ros

    environment:
      # Required for GUI
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    volumes:
      # Required for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${PWD}/entrypoint.sh:/entrypoint.sh
      - ${PWD}/../${PKG_NAME}:/root/dev_ws/src/${PKG_NAME}
      - ${PWD}/../my_interface:/root/dev_ws/src/my_interface

    tty: true
    stdin_open: true
    