services:
  ros:
    image: ncotti/ros2:first_steps

    build:
      context: .
      dockerfile: Dockerfile

    container_name: ros
    pull_policy: always

    environment:
      # Required for GUI
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

    volumes:
      # Required for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      - ${PWD}/entrypoint.sh:/entrypoint.sh
    
    tty: true
    stdin_open: true
    
